export const SCHEDULE_LOAD_USER_FROFILE = "SCHEDULE_LOAD_USER_FROFILE";
export const SCHEDULE_LOAD_USER_FROFILE_SUCCESS = "SCHEDULE_LOAD_USER_FROFILE_SUCCESS";

export const PROFILE_DO_LOGOUT = "PROFILE_DO_LOGOUT";
export const PROFILE_LOAD_USER_PROFILE = "PROFILE_LOAD_USER_PROFILE";
export const PROFILE_LOAD_USER_PROFILE_SUCCESS = "PROFILE_LOAD_USER_PROFILE_SUCCESS";
export const LOGIN_DO_LOGIN = "LOGIN_DO_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_RESET_LOGIN = "LOGIN_RESET_LOGIN";

export const DISEASE_MODAL_SAVE_DATA = "DISEASE_MODAL_SAVE_DATA";

export const CREATE_SCHEDULE_CREATE_DATA = "CREATE_SCHEDULE_CREATE_DATA";
export const CREATE_SCHEDULE_RESET_DATA = "CREATE_SCHEDULE_RESET_DATA";
export const CREATE_SCHEDULE_CREATE_DATA_SUCCESS = "CREATE_SCHEDULE_CREATE_DATA_SUCCESS";
export const CREATE_SCHEDULE_CREATE_DATA_FAIL = "CREATE_SCHEDULE_CREATE_DATA_FAIL";

//key examination schedule
export const EXAMINATION_SCHEDULE_LOAD_LIST_APPOINT = "EXAMINATION_SCHEDULE_LOAD_LIST_APPOINT";
export const EXAMINATION_SCHEDULE_LOAD_APPOINT_SUCCESS = "EXAMINATION_SCHEDULE_LOAD_APPOINT_SUCCESS";
export const EXAMINATION_SCHEDULE_LOAD_APPOINT_FAIL = "EXAMINATION_SCHEDULE_LOAD_APPOINT_FAIL";
export const EXAMINATION_SCHEDULE_RESET_LIST_APPOINT = "EXAMINATION_SCHEDULE_RESET_LIST_APPOINT";
export const EXAMINATION_SCHEDULE_LOAD_USER_APPOINT = "EXAMINATION_SCHEDULE_LOAD_USER_APPOINT";
export const EXAMINATION_SCHEDULE_RESET_LOADING = "EXAMINATION_SCHEDULE_RESET_LOADING";

//key update status examination schedule
export const EXAMINATION_SCHEDULE_UPDATE_STATUS = "EXAMINATION_SCHEDULE_UPDATE_STATUS";
export const EXAMINATION_SCHEDULE_UPDATE_STATUS_SUCCESS = "EXAMINATION_SCHEDULE_UPDATE_STATUS";
export const EXAMINATION_SCHEDULE_UPDATE_STATUS_FAIL = "EXAMINATION_SCHEDULE_UPDATE_STATUS";

//key work shedule
export const WORK_SCHEDULE_LOAD_DATA = "WORK_SCHEDULE_LOAD_DATA";
export const WORK_SCHEDULE_LOAD_DATA_SUCCESS = "WORK_SCHEDULE_LOAD_DATA_SUCCESS";
export const WORK_SCHEDULE_LOAD_DATA_FAIL = "WORK_SCHEDULE_LOAD_DATA_FAIL";
export const WORK_SCHEDULE_RESET_DATA = "WORK_SCHEDULE_RESET_DATA";
export const WORK_SCHEDULE_LOAD_ALL_PATIENTS = "WORK_SCHEDULE_LOAD_ALL_PATIENTS";
export const WORK_SCHEDULE_LOAD_ALL_PATIENTS_SUCCESS = "WORK_SCHEDULE_LOAD_ALL_PATIENTS_SUCCESS";
export const WORK_SCHEDULE_LOAD_ALL_PATIENTS_FAIL = "WORK_SCHEDULE_LOAD_ALL_PATIENTS_FAIL";
export const WORK_SCHEDULE_MESSAGE_EVENTS_CALLBACK = "WORK_SCHEDULE_MESSAGE_EVENTS_CALLBACK";

//key action handle videocall
//TYPE function handle call
export const VIDEO_CALL_CREATE_SOCKET_RTC = "VIDEO_CALL_CREATE_SOCKET_RTC";
export const VIDEO_CALL_MAKE_CALL = "VIDEO_CALL_MAKE_CALL";
export const VIDEO_CALL_FINISH_CALL = "VIDEO_CALL_FINISH_CALL";
export const VIDEO_CALL_RECEIVER_CALL = "VIDEO_CALL_RECEIVER_CALL";
export const VIDEO_CALL_SEND_MESSAGE = "VIDEO_CALL_SEND_MESSAGE";
export const VIDEO_CALL_DISCONNECT = "VIDEO_CALL_DISCONNECT";
export const VIDEO_CALL_CHANGE_LOCAL_STREAM = "VIDEO_CALL_CHANGE_LOCAL_STREAM";
export const VIDEO_CALL_ADD_NEW_FRIEND = "VIDEO_CALL_ADD_NEW_FRIEND";
export const VIDEO_CALL_RESET_MESSAGE_CALLBACK = "VIDEO_CALL_RESET_MESSAGE_CALLBACK";

//TYPE listener Receiver from videocall
export const VIDEO_CALL_LISTENER_GET_FRIEND_ONLINE = "VIDEO_CALL_LISTENER_GET_FRIEND_ONLINE";
export const VIDEO_CALL_LISTENER_NEW_FRIEND_ONLINE = "VIDEO_CALL_LISTENER_NEW_FRIEND_ONLINE";
export const VIDEO_CALL_LISTENER_DISCONECT_FRIEND = "VIDEO_CALL_LISTENER_DISCONECT_FRIEND";
export const VIDEO_CALL_START_CALL_SUCCESS = "VIDEO_CALL_START_CALL_SUCCESS";
export const VIDEO_CALL_LISTENER_END_CALL_SERVER = "VIDEO_CALL_LISTENER_END_CALL_SERVER";
export const VIDEO_CALL_LISTENER_NEW_CALL= "VIDEO_CALL_LISTENER_NEW_CALL";
export const VIDEO_CALL_LISTENER_NEW_MESSAGE = "VIDEO_CALL_LISTENER_NEW_MESSAGE";
export const VIDEO_CALL_LISTENER_BUSY_CALL = "VIDEO_CALL_LISTENER_BUSY_CALL";
export const VIDEO_CALL_ACTION_MESSAGE_CALLBACK = "VIDEO_CALL_ACTION_MESSAGE_CALLBACK";

//Type response data video 
export const VIDEO_CALL_DATA_VIDEO_LOCAL = "VIDEO_CALL_DATA_VIDEO_LOCAL";
export const VIDEO_CALL_DATA_VIDEO_SERVER = "VIDEO_CALL_DATA_VIDEO_SERVER";
export const VIDEO_CALL_RESET_DATA_SOCKET = "VIDEO_CALL_RESET_DATA_SOCKET";


//Type video call controller local video
export const VIDEO_CALL_SWITCH_CAMERA= "VIDEO_CALL_SWITCH_CAMERA";










