//key action type man hinh login
export const LOGIN_DO_LOGIN = "LOGIN_DO_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_RESET_LOGIN = "LOGIN_RESET_LOGIN";

//key action type màn hình đăng ký tài khoản
export const REGISTER_DO_REGISTER = "REGISTER_DO_REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_RESET_REGISTER = "REGISTER_RESET_REGISTER";

//key màn hình hiển thị tìm kiếm danh sách bác sĩ 
export const FETCH_ALL_DATA_SPECIALIZED = 'FETCH_ALL_DATA_SPECIALIZED';
export const FIND_DOCTOR_BY_SPEC_ID = 'FIND_DOCTOR_BY_SPEC_ID';
export const FETCH_SPACIALIZED_SUCCESS = "FETCH_SPACIALIZED_SUCCESS";
export const FETCH_DOCTOR_SUCCESS = "FETCH_DOCTOR_SUCCESS";
export const FETCH_SPACIALIZED_FAIL = "FETCH_SPACIALIZED_FAIL";
export const FETCH_DOCTOR_FAIL = "FETCH_DOCTOR_FAIL";
export const DOCTORLIST_LOAD_USER_FROFILE = "DOCTORLIST_LOAD_USER_FROFILE";
export const DOCTORLIST_LOAD_USER_FROFILE_SUCCESS = "DOCTORLIST_LOAD_USER_FROFILE_SUCCESS";
export const DOCTORLIST_PRESS_SELECT_DATE = "DOCTORLIST_PRESS_SELECT_DATE";
export const DOCTORLIST_PRESS_SELECT_IMMEDIATELY = "DOCTORLIST_PRESS_SELECT_IMMEDIATELY";

// Family manager action:
export const FAMILY_MANAGER_LOAD_ALL= "FAMILY_MANAGER_LOAD_ALL";
export const FAMILY_MANAGER_LOAD_ALL_RESET_OLD_DATA = "FAMILY_MANAGER_LOAD_ALL_RESET_OLD_DATA";
export const FAMILY_MANAGER_LOAD_ALL_SUCCESS = "FAMILY_MANAGER_LOAD_ALL_SUCCESS";
export const FAMILY_MANAGER_LOAD_ALL_FAIL = "FAMILY_MANAGER_LOAD_ALL_FAIL";

export const FAMILY_MANAGER_ADD_NEW_MEMBER = "FAMILY_MANAGER_ADD_NEW_MEMBER";
export const FAMILY_MANAGER_ADD_NEW_MEMBER_SUCCESS = "FAMILY_MANAGER_ADD_NEW_MEMBER_SUCCESS";
export const FAMILY_MANAGER_ADD_NEW_MEMBER_FAIL = "FAMILY_MANAGER_ADD_NEW_MEMBER_FAIL";
export const FAMILY_MANAGER_ADD_NEW_MEMBER_RESET = "FAMILY_MANAGER_ADD_NEW_MEMBER_RESET";

export const FAMILY_MANAGER_DO_DELETE= "FAMILY_MANAGER_DO_DELETE";
export const FAMILY_MANAGER_SUCCESS_DELETE= "FAMILY_MANAGER_SUCCESS_DELETE";
export const FAMILY_MANAGER_ERROR_DELETE= "FAMILY_MANAGER_ERROR_DELETE";
export const FAMILY_MANAGER_RESERT_DELETE= "FAMILY_MANAGER_RESERT_DELETE";

export const FAMILY_MANAGER_DO_UPDATE= "FAMILY_MANAGER_DO_UPDATE";
export const FAMILY_MANAGER_SUCCESS_DUPDATE= "FAMILY_MANAGER_SUCCESS_UPDATE";
export const FAMILY_MANAGER_ERROR_UPDATE= "FAMILY_MANAGER_ERROR_UPDATE";
export const FAMILY_MANAGER_RESERT_UPDATE= "FAMILY_MANAGER_RESERT_UPDATE";

//key màn hình đặt lịch khám trước
export const BOOKING_CHECK_TIME_AVAILABLE = "BOOKING_CHECK_TIME_AVAILABLE";
export const BOOKING_GET_TIME_SUCCESS = "BOOKING_GET_TIME_SUCCESS";
export const BOOKING_GET_TIME_FAIL = "BOOKING_GET_TIME_FAIL";
export const BOOKING_CLICK_ITEM_TIME = "BOOKING_CLICK_ITEM_TIME";
export const BOOKING_SET_DATA_USERNAME = "BOOKING_SET_DATA_USERNAME";
export const BOOKING_SAVE_DATA_APPOINTMENT = "BOOKING_SAVE_DATA_APPOINTMENT";
export const BOOKING_SAVE_DATA_SUCCESS = "BOOKING_SAVE_DATA_SUCCESS";
export const BOOKING_SAVE_DATA_FAIL = "BOOKING_SAVE_DATA_FAIL";
export const BOOKING_RESET_LOADING = "BOOKING_RESET_LOADING";
export const CONSULTANT_SELECT_ONCLICK_ITEM = "CONSULTANT_SELECT_ONCLICK_ITEM";
export const BOOKING_RESET_DATA = "BOOKING_RESET_DATA";

//key get date appointment of doctor
export const BOOKING_GET_DATA_SCHEDULE = "BOOKING_GET_DATA_SCHEDULE";
export const BOOKING_GET_DATA_SCHEDULE_SUCCESS = "BOOKING_GET_DATA_SCHEDULE_SUCCESS";
export const BOOKING_GET_DATA_SCHEDULE_FAIL = "BOOKING_GET_DATA_SCHEDULE_FAIL";
export const BOOKING_RESET_DATA_SCHEDULE = "BOOKING_RESET_DATA_SCHEDULE";

//key màn hình chọn tên để đặt lịch khám, tên người dùng hoặc tên thành viên gia đình
export const SELECT_NAME_FETCH_NAME = "SELECT_NAME_FETCH_NAME";
export const SELECT_NAME_RESET_OLD_DATA = "SELECT_NAME_RESET_OLD_DATA";
export const SELECT_NAME_FETCH_NAME_SUCCESS = "SELECT_NAME_FETCH_NAME_SUCCESS";
export const SELECT_NAME_FETCH_NAME_FAIL = "SELECT_NAME_FETCH_NAME_FAIL";
export const SELECT_NAME_CLICK_ITEM = "SELECT_NAME_CLICK_ITEM";

//key màn hình thêm mới thành viên gia đình
export const ADD_MEMBER_FAMILY = "ADD_MEMBER_FAMILY";
export const ADD_MEMBER_FAMILY_SUCCESS = "ADD_MEMBER_FAMILY_SUCCESS";
export const ADD_MEMBER_FAMILY_FAIL = "ADD_MEMBER_FAMILY_FAIL";
export const ADD_MEMBER_FAMILY_RESET = "ADD_MEMBER_FAMILY_RESET";

//key màn hình chọn loại bệnh khám khi đặt hẹn
export const SELECT_DISEASE_ONCLICK_ITEM = "SELECT_DISEASE_ONCLICK_ITEM";
export const SELECT_DISEASE_PUSH_TO_BOOKING = "SELECT_DISEASE_PUSH_TO_BOOKING";

//key màn hình hiển thị thông tin cá nhân, thay đổi thông tin cá nhân
export const USER_PROFILE_DO_LOGOUT = "USER_PROFILE_DO_LOGOUT";
export const USER_PROFILE_UPLOAD_AVATA = "USER_PROFILE_UPLOAD_AVATA";
export const USER_PROFILE_CHANGE_AVATA= "USER_PROFILE_CHANGE_AVATA";
export const USER_PROFILE_CHANGE_AVATA_SUCCESS = "USER_PROFILE_CHANGE_AVATA_SUCCESS";
export const USER_PROFILE_CHANGE_AVATA_FAIL = "USER_PROFILE_CHANGE_AVATA_FAIL";

// key action setting notification creen 
export const SETTING_NOTIFICATION_GET_DATA = "SETTING_NOTIFICATION_GET_DATA";
export const SETTING_NOTIFICATION_GET_DATA_SUCCESS = "SETTING_NOTIFICATION_GET_DATA_SUCCESS";
export const SETTING_NOTIFICATION_GET_DATA_FAIL = "SETTING_NOTIFICATION_GET_DATA_FAIL";

export const SETTING_NOTIFICATION_SAVE_DATA = "SETTING_NOTIFICATION_SAVE_DATA";
export const SETTING_NOTIFICATION_SAVE_DATA_SUCCESS = "SETTING_NOTIFICATION_SAVE_DATA_SUCCESS";
export const SETTING_NOTIFICATION_SAVE_DATA_FAIL = "SETTING_NOTIFICATION_SAVE_DATA_FAIL";

// key for type update user info screen
export const USER_MANAGER_UPDATE_USER = "USER_MANAGER_UPDATE_USER";
export const USER_MANAGER_UPDATE_USER_SUCCESS = "USER_MANAGER_UPDATE_USER_SUCCESS";
export const USER_MANAGER_UPDATE_USER_FAIL = "USER_MANAGER_UPDATE_USER_FAIL";
export const USER_MANAGER_UPDATE_USER_RESET = "USER_MANAGER_UPDATE_USER_RESET";
export const EDIT_USER_SUCCESS= "USER_MANAGER_UPDATE_USER_RESET";


// key for request reset password screen
export const RESET_PASSWORD_DO_RESET_PASSWORD = "RESET_PASSWORD_DO_RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
export const RESET_PASSWORD_DO_RESET = "RESET_PASSWORD_DO_RESET";

// key for change password screen
export const CHANGE_PASSWORD_DO_CHANGE= "CHANGE_PASSWORD_DO_CHANGE";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";
export const CHANGE_PASSWORD_DO_RESET = "CHANGE_PASSWORD_DO_RESET";



