export const FETCH_ALL_DATA_SPECIALIZED = 'FETCH_ALL_DATA_SPECIALIZED';
export const FIND_DOCTOR_BY_ID = 'FIND_DOCTOR_BY_ID';
export const FETCH_SPACIALIZED_SUCCESS = "FETCH_SPACIALIZED_SUCCESS";
export const FETCH_DOCTOR_SUCCESS = "FETCH_DOCTOR_SUCCESS";
export const FETCH_SPACIALIZED_FAIL = "FETCH_SPACIALIZED_FAIL";
export const FETCH_DOCTOR_FAIL = "FETCH_DOCTOR_FAIL";
export const SCHEDULE_LOAD_USER_FROFILE = "SCHEDULE_LOAD_USER_FROFILE";
export const SCHEDULE_LOAD_USER_FROFILE_SUCCESS = "SCHEDULE_LOAD_USER_FROFILE_SUCCESS";
export const SCHEDULE_PRESS_SELECT_DATE = "SCHEDULE_PRESS_SELECT_DATE";
export const SCHEDULE_PRESS_SELECT_IMMEDIATELY = "SCHEDULE_PRESS_SELECT_IMMEDIATELY";

//Message event load data doctor, for check session doctor online or offline
export const SCHEDULE_MESSAGE_EVENTS_CALLBACK= "SCHEDULE_MESSAGE_EVENTS_CALLBACK";

export const APPOINTMENT_CHECK_TIME_AVAILABLE = "APPOINTMENT_CHECK_TIME_AVAILABLE";
export const APPOINTMENT_GET_TIME_SUCCESS = "APPOINTMENT_GET_TIME_SUCCESS";
export const APPOINTMENT_GET_TIME_FAIL = "APPOINTMENT_GET_TIME_FAIL";
export const APPOINTMENT_CLICK_ITEM_TIME = "APPOINTMENT_CLICK_ITEM_TIME";
export const APPOINTMENT_CLICK_ITEM_CONSULT_TYPE = "APPOINTMENT_CLICK_ITEM_CONSULT_TYPE";
export const APPOINTMENT_SET_DATA_USERNAME = "APPOINTMENT_SET_DATA_USERNAME";
export const APPOINTMENT_SAVE_DATA_APPOINTMENT = "APPOINTMENT_SAVE_DATA_APPOINTMENT";
export const APPOINTMENT_SAVE_DATA_SUCCESS = "APPOINTMENT_SAVE_DATA_SUCCESS";
export const APPOINTMENT_SAVE_DATA_FAIL = "APPOINTMENT_SAVE_DATA_FAIL";
export const APPOINTMENT_RESET_LOADING = "APPOINTMENT_RESET_LOADING";
export const CONSULTANT_MODAL_ONCLICK_ITEM = "CONSULTANT_MODAL_ONCLICK_ITEM";
export const APPOINTMENT_RESET_DATA = "APPOINTMENT_RESET_DATA";

//key get date appointment of doctor
export const APPOINTMENT_GET_DATA_SCHEDULE = "APPOINTMENT_GET_DATA_SCHEDULE";
export const APPOINTMENT_GET_DATA_SCHEDULE_SUCCESS = "APPOINTMENT_GET_DATA_SCHEDULE_SUCCESS";
export const APPOINTMENT_GET_DATA_SCHEDULE_FAIL = "APPOINTMENT_GET_DATA_SCHEDULE_FAIL";
export const APPOINTMENT_RESET_DATA_SCHEDULE = "APPOINTMENT_RESET_DATA_SCHEDULE";

export const MODAL_NAME_FETCH_NAME = "MODAL_NAME_FETCH_NAME";
export const MODAL_NAME_RESET_OLD_DATA = "MODAL_NAME_RESET_OLD_DATA";
export const MODAL_NAME_FETCH_NAME_SUCCESS = "MODAL_NAME_FETCH_NAME_SUCCESS";
export const MODAL_NAME_FETCH_NAME_FAIL = "MODAL_NAME_FETCH_NAME_FAIL";
export const MODAL_NAME_CLICK_ITEM = "MODAL_NAME_CLICK_ITEM";
export const MODAL_NAME_ADD_NEW_MEMBER = "MODAL_NAME_ADD_NEW_MEMBER";
export const MODAL_NAME_ADD_NEW_MEMBER_SUCCESS = "MODAL_NAME_ADD_NEW_MEMBER_SUCCESS";
export const MODAL_NAME_ADD_NEW_MEMBER_FAIL = "MODAL_NAME_ADD_NEW_MEMBER_FAIL";
export const MODAL_NAME_ADD_NEW_MEMBER_RESET = "MODAL_NAME_ADD_NEW_MEMBER_RESET";

export const APPOINTMENT_FETCH_APPOINTMENT_FOR = "APPOINTMENT_FETCH_APPOINTMENT_FOR";
export const APPOINTMENT_APPOINTMENT_SUCCESS = "APPOINTMENT_APPOINTMENT_SUCCESS";
export const APPOINTMENT_APPOINTMENT_FAIL = "APPOINTMENT_APPOINTMENT_FAIL";

export const STARTSCREEN_LOGIN_FACEBOOK = "STARTSCREEN_LOGIN_FACEBOOK";
export const STARTSCREEN_LOGIN_SOCIAL_SUCCESS = "STARTSCREEN_LOGIN_SOCIAL_SUCCESS";
export const STARTSCREEN_LOGIN_FACEBOOK_FAIL = "STARTSCREEN_LOGIN_FACEBOOK_FAIL";
export const STARTSCREEN_LOGIN_FACEBOOK_RESET = "STARTSCREEN_LOGIN_FACEBOOK_RESET";
export const STARTSCREEN_LOGIN_GOOGLE = "STARTSCREEN_LOGIN_GOOGLE";
export const STARTSCREEN_LOGIN_GOOGLE_FAIL = "STARTSCREEN_LOGIN_GOOGLE_FAIL";
export const STARTSCREEN_LOGIN_GOOGLE_RESET = "STARTSCREEN_LOGIN_GOOGLE_RESET";
export const STARTSCREEN_CONFIG_LOGIN_GOOGLE = "STARTSCREEN_CONFIG_LOGIN_GOOGLE";

export const PROFILE_DO_LOGOUT = "PROFILE_DO_LOGOUT";

export const LOGIN_DO_LOGIN = "LOGIN_DO_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_RESET_LOGIN = "LOGIN_RESET_LOGIN";

export const REGISTER_DO_REGISTER = "REGISTER_DO_REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_RESET_REGISTER = "REGISTER_RESET_REGISTER";

export const RESET_PASSWORD_DO_RESET_PASSWORD = "RESET_PASSWORD_DO_RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
export const RESET_PASSWORD_DO_RESET = "RESET_PASSWORD_DO_RESET";

export const CHANGE_PASSWORD_DO_CHANGE= "CHANGE_PASSWORD_DO_CHANGE";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";
export const CHANGE_PASSWORD_DO_RESET = "CHANGE_PASSWORD_DO_RESET";

//key action for schedule manager screen
export const SCHEDULE_MANAGER_DELETE_APPOINT = "SCHEDULE_MANAGER_DELETE_APPOINT";
export const SCHEDULE_MANAGER_DELETE_APPOINT_SUCCESS = "SCHEDULE_MANAGER_DELETE_APPOINT_SUCCESS";
export const SCHEDULE_MANAGER_DELETE_APPOINT_FAIL = "SCHEDULE_MANAGER_DELETE_APPOINT_FAIL";
export const SCHEDULE_MANAGER_GET_LIST_APPOINT = "SCHEDULE_MANAGER_GET_LIST_APPOINT";
export const SCHEDULE_MANAGER_GET_LIST_APPOINT_SUCCESS = "SCHEDULE_MANAGER_GET_LIST_APPOINT_SUCCESS";
export const SCHEDULE_MANAGER_GET_LIST_APPOINT_FAIL = "SCHEDULE_MANAGER_GET_LIST_APPOINT_FAIL";
export const SCHEDULE_MANAGER_RESET_DATA = "SCHEDULE_MANAGER_RESET_DATA";
export const RESET_ALL_DATA = "RESET_ALL_DATA";

//key action handle videocall
//TYPE function handle call
export const VIDEO_CALL_CREATE_SOCKET_RTC = "VIDEO_CALL_CREATE_SOCKET_RTC";
export const VIDEO_CALL_MAKE_CALL = "VIDEO_CALL_MAKE_CALL";
export const VIDEO_CALL_FINISH_CALL = "VIDEO_CALL_FINISH_CALL";
export const VIDEO_CALL_RECEIVER_CALL = "VIDEO_CALL_RECEIVER_CALL";
export const VIDEO_CALL_SEND_MESSAGE = "VIDEO_CALL_SEND_MESSAGE";
export const VIDEO_CALL_DISCONNECT = "VIDEO_CALL_DISCONNECT";
export const VIDEO_CALL_CHANGE_LOCAL_STREAM = "VIDEO_CALL_CHANGE_LOCAL_STREAM";
export const VIDEO_CALL_ADD_NEW_FRIEND = "VIDEO_CALL_ADD_NEW_FRIEND";

//TYPE listener Receiver from videocall
export const VIDEO_CALL_LISTENER_GET_FRIEND_ONLINE = "VIDEO_CALL_LISTENER_GET_FRIEND_ONLINE";
export const VIDEO_CALL_LISTENER_NEW_FRIEND_ONLINE = "VIDEO_CALL_LISTENER_NEW_FRIEND_ONLINE";
export const VIDEO_CALL_LISTENER_DISCONECT_FRIEND = "VIDEO_CALL_LISTENER_DISCONECT_FRIEND";
export const VIDEO_CALL_START_CALL_SUCCESS = "VIDEO_CALL_START_CALL_SUCCESS";
export const VIDEO_CALL_LISTENER_END_CALL_SERVER = "VIDEO_CALL_LISTENER_END_CALL_SERVER";
export const VIDEO_CALL_LISTENER_NEW_CALL= "VIDEO_CALL_LISTENER_NEW_CALL";
export const VIDEO_CALL_LISTENER_NEW_MESSAGE = "VIDEO_CALL_LISTENER_NEW_MESSAGE";
export const VIDEO_CALL_LISTENER_BUSY_CALL = "VIDEO_CALL_LISTENER_BUSY_CALL";
export const VIDEO_CALL_ACTION_MESSAGE_CALLBACK = "VIDEO_CALL_ACTION_MESSAGE_CALLBACK";
export const VIDEO_CALL_RESET_MESSAGE_CALLBACK = "VIDEO_CALL_RESET_MESSAGE_CALLBACK";
export const VIDEO_CALL_DISCONNECT_SOCKET = "VIDEO_CALL_DISCONNECT_SOCKET";
export const VIDEO_CALL_ONCONNECT_SOCKET = "VIDEO_CALL_ONCONNECT_SOCKET";

//Type response data video 
export const VIDEO_CALL_DATA_VIDEO_LOCAL = "VIDEO_CALL_DATA_VIDEO_LOCAL";
export const VIDEO_CALL_DATA_VIDEO_SERVER = "VIDEO_CALL_DATA_VIDEO_SERVER";
export const VIDEO_CALL_RESET_DATA_SOCKET = "VIDEO_CALL_RESET_DATA_SOCKET";

//Type video call controller local video
export const VIDEO_CALL_SWITCH_CAMERA = "VIDEO_CALL_SWITCH_CAMERA";
export const VIDEO_CALL_CAM_CONTROL = "VIDEO_CALL_CAM_CONTROL";
export const VIDEO_CALL_MIC_CONTROL = "VIDEO_CALL_MIC_CONTROL";
export const VIDEO_CALL_SOUND_CONTROL = "VIDEO_CALL_SOUND_CONTROL";

//Type videocall get all doctors
export const VIDEO_CALL_GET_ALL_DOCTOR = "VIDEO_CALL_GET_ALL_DOCTOR";
export const VIDEO_CALL_GET_ALL_DOCTOR_SUCCESS = "VIDEO_CALL_GET_ALL_DOCTOR_SUCCESS";
export const VIDEO_CALL_NEW_DOCTOR_ONLINE = "VIDEO_CALL_NEW_DOCTOR_ONLINE";
export const VIDEO_CALL_NEW_DOCTOR_OFFLINE = "VIDEO_CALL_NEW_DOCTOR_OFFLINE";







