export default {
    Screen_StartScreen : "StartScreen",
    Screen_LoginScreen : "LoginScreen",
    Screen_RegisterScreen : "RegisterScreen",
    Screen_HelpScreen : "HelpScreen",
    Screen_TermOfServiceScreen : "TermOfServiceScreen",
    Screen_MainScreen: "MainScreen",
    Screen_DoctorList: "DoctorListScreen",
    Screen_Booking: "BookingScreen",
    Screen_UserProfile: "UserProfileScreen",
    Screen_SettingNotification:"SettingNotification",
    Screen_FamilyManager:"FamilyManger",
    Screen_EditFamilyMember:"EditFamilyMember",
    Screen_UserManager:"UserManager",
    Screen_ResetPassword:"ResetPassword",
    Screen_ChangePassword:"ChangePassword",
};