export default {
    KEY_STORE_USER_PROFILE : "key_store_user_profile",
    //using just ios
    KEY_CLIENT_ID_LOGIN_GOOGLE: "79233148802-k4or16n5ki5ejmtqogut9d96ejvg7hse.apps.googleusercontent.com",
    VALIDATE_PASSWORD: "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[a-zA-Z\\d]{8,}$",
    DEFAULT_SYMPLE_DATE: "YYYY-MM-DD",
    KEY_INTENT_USER_NAME: "intent_userName",
    KEY_INTENT_USER_ID: "intent_userID",
    KEY_INTENT_DATA_DOCTOR: "intent_dataDoctor",
    KEY_INTENT_SELECT_DATE: "selectDate",
    KEY_STORE_TOKEN: "key_store_token",
    KEY_USER_ID: "key_store_user_id",
    TYPE_CONFIRM: 0,
    TYPE_CALL_NOW: 1,
    TYPE_DECLINE: 2,
    TYPE_DOCTOR: 0,
    TYPE_PATIENT: 1,
    TYPE_REFRESH_DATA_APPOINT: "type_refresh_data_appoint",
    VIDEOCALL_LISTENER_START_CALL_SUCCESS: "VIDEOCALL_LISTENER_START_CALL_SUCCESS",
    VIDEOCALL_LISTENER_DISCONNECT_FRIEND: "VIDEOCALL_LISTENER_DISCONNECT_FRIEND",
    VIDEOCALL_LISTENER_ENDCALL_CB: "VIDEOCALL_LISTENER_ENDCALL_CB",
    VIDEOCALL_LISTENER_NEW_CALL_CB: "VIDEOCALL_LISTENER_NEW_CALL_CB",
    VIDEOCALL_LISTENER_NEW_MESSAGE_CB: "VIDEOCALL_LISTENER_NEW_MESSAGE_CB",
    VIDEOCALL_LISTENER_BUSY_CB: "VIDEOCALL_LISTENER_BUSY_CB",
    //type nhận được từ bác sĩ, trường hợp bác sĩ đồng ý khám hoặc từ chối
    VIDEOCALL_SEND_MSG_CONFIRM_CALL: "VIDEOCALL_SEND_MSG_CONFIRM_CALL",
    VIDEOCALL_SEND_MSG_DECLINE_CALL: "VIDEOCALL_SEND_MSG_DECLINE_CALL",
    //type gửi đi từ bệnh nhân, sau khi gửi request đặt hẹn thành công
    VIDEOCALL_SEND_MSG_REQ_APPOINT: "VIDEOCALL_SEND_MSG_REQ_APPOINT",
    SCHEDULE_EVENT_LOAD_DOCTORS_SUCCESS: "SCHEDULE_EVENT_LOAD_DOCTORS_SUCCESS",

    KEY_STORE_SETTING_NOTIFICATION : "key_store_setting_notification",
};