//key action type man hinh login
export const LOGIN_DO_LOGIN = "LOGIN_DO_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_RESET_LOGIN = "LOGIN_RESET_LOGIN";

//key action type màn hình quản lí lịch làm việc bác sĩ
export const WORK_SCHEDULE_LOAD_DATA = "WORK_SCHEDULE_LOAD_DATA";
export const WORK_SCHEDULE_LOAD_DATA_SUCCESS = "WORK_SCHEDULE_LOAD_DATA_SUCCESS";
export const WORK_SCHEDULE_LOAD_DATA_FAIL = "WORK_SCHEDULE_LOAD_DATA_FAIL";
export const WORK_SCHEDULE_RESET_DATA = "WORK_SCHEDULE_RESET_DATA";

//key action type màn hình tạo lịch làm việc
export const CREATE_SCHEDULE_CREATE_DATA = "CREATE_SCHEDULE_CREATE_DATA";
export const CREATE_SCHEDULE_RESET_DATA = "CREATE_SCHEDULE_RESET_DATA";
export const CREATE_SCHEDULE_CREATE_DATA_SUCCESS = "CREATE_SCHEDULE_CREATE_DATA_SUCCESS";
export const CREATE_SCHEDULE_CREATE_DATA_FAIL = "CREATE_SCHEDULE_CREATE_DATA_FAIL";

// key action for : doctor info manager screen
export const DOCTOR_INFO_MANAGER_DO_GET_DATA = "DOCTOR_INFO_MANAGER_DO_GET_DATA";
export const DOCTOR_INFO_MANAGER_DO_GET_DATA_SUCCESS = "DOCTOR_INFO_MANAGER_DO_GET_DATA_SUCCESS";
export const DOCTOR_INFO_MANAGER_DO_GET_DATA_RESET = "DOCTOR_INFO_MANAGER_DO_GET_DATA_RESET";
export const DOCTOR_INFO_MANAGER_DO_GET_DATA_ERROR = "DOCTOR_INFO_MANAGER_DO_GET_DATA_ERROR";
export const DOCTOR_INFO_MANAGER_DO_UPDATE_DATA = "DOCTOR_INFO_MANAGER_DO_UPDATE_DATA";
export const DOCTOR_INFO_MANAGER_DO_UPDATE_DATA_SUCCESS = "DOCTOR_INFO_MANAGER_DO_UPDATE_DATA_SUCCESS";
export const DOCTOR_INFO_MANAGER_DO_UPDATE_DATA_ERROR = "DOCTOR_INFO_MANAGER_DO_UPDATE_DATA_ERROR";
export const DOCTOR_INFO_MANAGER_DO_UPDATE_DATA_RESET = "DOCTOR_INFO_MANAGER_DO_UPDATE_DATA_RESET";

// key action setting notification creen 
export const SETTING_NOTIFICATION_GET_DATA = "SETTING_NOTIFICATION_GET_DATA";
export const SETTING_NOTIFICATION_GET_DATA_SUCCESS = "SETTING_NOTIFICATION_GET_DATA_SUCCESS";
export const SETTING_NOTIFICATION_GET_DATA_FAIL = "SETTING_NOTIFICATION_GET_DATA_FAIL";

export const SETTING_NOTIFICATION_SAVE_DATA = "SETTING_NOTIFICATION_SAVE_DATA";
export const SETTING_NOTIFICATION_SAVE_DATA_SUCCESS = "SETTING_NOTIFICATION_SAVE_DATA_SUCCESS";
export const SETTING_NOTIFICATION_SAVE_DATA_FAIL = "SETTING_NOTIFICATION_SAVE_DATA_FAIL";

//key action cho man hinh profile
export const PROFILE_DO_LOGOUT = "PROFILE_DO_LOGOUT";
export const PROFILE_LOAD_USER_PROFILE = "PROFILE_LOAD_USER_PROFILE";
export const PROFILE_LOAD_USER_PROFILE_SUCCESS = "PROFILE_LOAD_USER_PROFILE_SUCCESS";

// key action cho man hinh reset password
export const RESET_PASSWORD_DO_RESET_PASSWORD = "RESET_PASSWORD_DO_RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
export const RESET_PASSWORD_DO_RESET = "RESET_PASSWORD_DO_RESET";

// key action cho man hinh change password
export const CHANGE_PASSWORD_DO_CHANGE= "CHANGE_PASSWORD_DO_CHANGE";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";
export const CHANGE_PASSWORD_DO_RESET = "CHANGE_PASSWORD_DO_RESET";


